version: 2.1

description: |
  Build and publish hybrid Apps based on Ionic for iOS / Android
  Repository: https://github.com/okode/orbs

cache-key-gradle: &cache-key-gradle
  key: cache-gradle-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "plugins/fetch.json" }}

cache-key-cocoapods: &cache-key-cocoapods
  key: cache-cocoapods-{{ .Environment.CIRCLE_JOB }}-{{ checksum "plugins/fetch.json" }}

orbs:
  common: okode/common@dev:first

executors:
  node:
    docker:
      - image: circleci/node:12
  java-node:
    docker:
      - image: circleci/openjdk:8-node-browsers
  android:
    docker:
      - image: circleci/android:api-28-node
  ios:
    macos:
      xcode: "10.2.1"

jobs:
  test:
    parameters:
      skip-tests:
        type: boolean
        default: false
      skip-lint:
        type: boolean
        default: false
    executor: java-node
    steps:
      - checkout
      - common/node-upgrade
      - common/npm-install
      - run:
          name: Building
          command: npm run build -- --progress false --aot
      - unless:
          condition: << parameters.skip-tests >>
          steps:
            - common/chrome-upgrade
            - run:
                name: Running unit tests
                command: npm run test -- --configuration ci
            - run:
                name: Running e2e tests
                command: npm run e2e
            - store_test_results:
                path: test-results
      - unless:
          condition: << parameters.skip-lint >>
          steps:
            - run:
                name: Running lint
                command: npx ng lint --force --format=json app > lint-results.json
      - common/sonar
  pwa:
    executor: node
    steps:
      - checkout
      - common/npm-install
      - run:
          name: Building
          command: npm run build -- --progress false --prod
      - persist_to_workspace:
          root: .
          paths:
            - www
  ios:
    parameters:
      attach-workspace:
        type: boolean
        default: false
      dev-signing-password:
        type: string
      dist-signing-password:
        type: string
      pod-setup:
        type: boolean
        default: false
    executor: ios
    steps:
      - checkout
      - common/npm-install
      - run:
          name: Installing CI dependencies
          command: npx cci ci install
      - run:
          name: Installing Certificates
          command: npx cci ci keychain << parameters.dev-signing-password >> << parameters.dist-signing-password >>
      - when:
          condition: << parameters.pod-setup >>
          steps:
            - restore_cache:
                << : *cache-key-cocoapods
            - run:
                name: Installing Cocoapods dependencies
                command: pod setup
      - when:
          condition: << parameters.attach-workspace >>
          steps:
            - attach_workspace:
                at: .
            - run:
                name: Clearing sourcemaps
                command: find www -name *.map -type f -delete
      - run:
          name: Building
          command: scripts/build.sh
          no_output_timeout: 30m
      - persist_to_workspace:
          root: .
          paths:
            - output
      - when:
          condition: << parameters.pod-setup >>
          steps:
            - run:
                name: Restoring plugins/fetch.json
                command: git checkout plugins/fetch.json
            - save_cache:
                << : *cache-key-cocoapods
                paths:
                  - ~/.cocoapods
      - run:
          name: Deploying
          command: scripts/deploy.sh
  android:
    parameters:
      attach-workspace:
        type: boolean
        default: false
    executor: android
    steps:
      - checkout
      - common/node-upgrade
      - common/npm-install
      - run:
          name: Installing CI dependencies
          command: npx cci ci install
      - restore_cache:
          << : *cache-key-gradle
      - when:
          condition: << parameters.attach-workspace >>
          steps:
            - attach_workspace:
                at: .
            - run:
                name: Clearing sourcemaps
                command: find www -name *.map -type f -delete
      - run:
          name: Building
          command: scripts/build.sh
          no_output_timeout: 30m
      - persist_to_workspace:
          root: .
          paths:
            - output
      - run:
          name: Restoring plugins/fetch.json
          command: git checkout plugins/fetch.json
      - save_cache:
          << : *cache-key-gradle
          paths:
            - ~/.gradle/caches
      - run:
          name: Deploying
          command: scripts/deploy.sh
