version: 2.1

description: |
  Build and publish hybrid Apps based on Ionic for iOS / Android
  Repository: https://github.com/okode/orbs

cache-key-gradle: &cache-key-gradle
  key: cache-gradle-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package-lock.json" }}

cache-key-cocoapods: &cache-key-cocoapods
  key: cache-cocoapods-{{ .Environment.CIRCLE_JOB }}-{{ checksum "<< parameters.cocoapods-lock-path >>" }}

orbs:
  common: okode/common@dev:first

executors:
  node:
    docker:
      - image: circleci/node:12
  java-node:
    docker:
      - image: circleci/openjdk:8-node-browsers
  android:
    docker:
      - image: circleci/android:api-28-node
  ios:
    macos:
      xcode: "10.2.1"

commands:
  install:
    description: Install Ionic requirements
    parameters:
      cordova-version:
        type: string
        default: "8"
    steps:
      - run:
          name: Installing Ionic requirements
          command: |
            PLATFORM=${CIRCLE_JOB}
            if [[ $PLATFORM == "ios" ]]; then
              sudo gem install fastlane
              npm install --quiet -g ionic cordova@<< parameters.cordova-version >>
            fi
            if [[ $PLATFORM == "android" ]]; then
              sudo npm install --quiet -g ionic cordova@<< parameters.cordova-version >>
              yes | sdkmanager --licenses || true
              yes | sdkmanager "build-tools;28.0.3" || true
              yes | sdkmanager "platforms;android-28" || true
              yes | sdkmanager "platform-tools" || true
              yes | sdkmanager "tools" || true
              if [[ $CIRCLE_TAG == *-dist ]]; then
                gem install fastlane -NV
              fi
            fi
jobs:
  test:
    parameters:
      skip-tests:
        type: boolean
        default: false
      skip-lint:
        type: boolean
        default: false
      skip-sonar:
        type: boolean
        default: false
      persist-results:
        type: boolean
        default: false
    executor: java-node
    steps:
      - checkout
      - common/node-upgrade
      - common/npm-install
      - run:
          name: Building
          command: npm run build -- --progress false --aot
      - unless:
          condition: << parameters.skip-tests >>
          steps:
            - common/chrome-upgrade
            - run:
                name: Running unit tests
                command: npm run test -- --configuration ci
            - run:
                name: Running e2e tests
                command: npm run e2e
            - store_test_results:
                path: test-results
      - unless:
          condition: << parameters.skip-lint >>
          steps:
            - run:
                name: Running lint
                command: npx ng lint --force --format=json app > lint-results.json
      - unless:
          condition: << parameters.skip-sonar >>
          steps:
            - common/sonar
      - when:
          condition: << parameters.persist-results >>
          steps:
            - persist_to_workspace:
                root: .
                paths:
                  - node_modules
                  - test-results
                  - lint-results.json
                  - coverage
                  - www
  pwa:
    executor: node
    steps:
      - checkout
      - common/npm-install
      - run:
          name: Building
          command: npm run build -- --progress false --prod
      - persist_to_workspace:
          root: .
          paths:
            - www
  ios:
    parameters:
      attach-workspace:
        type: boolean
        default: false
      dev-signing-password:
        type: string
      dist-signing-password:
        type: string
      cocoapods-lock-path:
        type: string
        default: ''
      cordova-version:
        type: string
        default: "8"
    executor: ios
    steps:
      - checkout
      - common/npm-install
      - install:
          cordova-version: << parameters.cordova-version >>
      - run:
          name: Installing Certificates
          command: npx cci ci keychain << parameters.dev-signing-password >> << parameters.dist-signing-password >>
      - when:
          condition: << parameters.cocoapods-lock-path >>
          steps:
            - restore_cache:
                << : *cache-key-cocoapods
            - run:
                name: Installing Cocoapods dependencies
                command: pod setup
      - when:
          condition: << parameters.attach-workspace >>
          steps:
            - attach_workspace:
                at: .
            - run:
                name: Clearing sourcemaps
                command: find www -name *.map -type f -delete
      - run:
          name: Building
          command: scripts/build.sh
          no_output_timeout: 30m
      - persist_to_workspace:
          root: .
          paths:
            - output
      - when:
          condition: << parameters.cocoapods-lock-path >>
          steps:
            - run:
                name: Restoring << parameters.cocoapods-lock-path >>
                command: git checkout << parameters.cocoapods-lock-path >>
            - save_cache:
                << : *cache-key-cocoapods
                paths:
                  - ~/.cocoapods
      - run:
          name: Deploying
          command: scripts/deploy.sh
  android:
    parameters:
      attach-workspace:
        type: boolean
        default: false
      cordova-version:
        type: string
        default: "8"
    executor: android
    steps:
      - checkout
      - common/node-upgrade
      - common/npm-install
      - install:
          cordova-version: << parameters.cordova-version >>
      - restore_cache:
          << : *cache-key-gradle
      - when:
          condition: << parameters.attach-workspace >>
          steps:
            - attach_workspace:
                at: .
            - run:
                name: Clearing sourcemaps
                command: find www -name *.map -type f -delete
      - run:
          name: Building
          command: scripts/build.sh
          no_output_timeout: 30m
      - persist_to_workspace:
          root: .
          paths:
            - output
      - run:
          name: Restoring package-lock.json
          command: git checkout package-lock.json
      - save_cache:
          << : *cache-key-gradle
          paths:
            - ~/.gradle/caches
      - run:
          name: Deploying
          command: scripts/deploy.sh
