version: 2.1

description: |
  Build fullstack applications based on Ionic and Spring Boot
  Repository: https://github.com/okode/orbs

cache-key-npm: &cache-key-npm
  key: cache-npm-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package-lock.json" }}

cache-key-gradle: &cache-key-gradle
  key: cache-gradle-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "build.gradle" }}

cache-key-sonar: &cache-key-sonar
  key: cache-sonar-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "sonar-project.properties" }}

executors:
  java-node:
    docker:
      - image: circleci/openjdk:8-node-browsers

commands:
  scan:
    steps:
      - run:
          name: Download Sonar scanner
          command: curl -L http://central.maven.org/maven2/org/sonarsource/scanner/cli/sonar-scanner-cli/3.3.0.1492/sonar-scanner-cli-3.3.0.1492.jar > sonar-scanner.jar
      - restore_cache:
          << : *cache-key-sonar
      - run:
          name: Scanning
          command: java -jar sonar-scanner.jar
      - save_cache:
          << : *cache-key-sonar
          paths:
            - ~/.sonar

jobs:
  app:
    parameters:
      path:
        type: string
        default: app
      package:
        type: boolean
        default: false
    executor: java-node
    working_directory: ~/project/<< parameters.path >>
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          << : *cache-key-npm
      - run:
          name: Installing NPM dependencies
          command: if [ ! -d "node_modules" ]; then npm ci; fi
      - run:
          name: Restoring package-lock.json
          command: git checkout package-lock.json
      - save_cache:
          << : *cache-key-npm
          paths:
            - node_modules
      - when:
          condition: << parameters.package >>
          steps:
            - run:
                name: Installing Ionic
                command: sudo npm install -g ionic
            - run:
                name: Building
                command: ionic build --prod
            - persist_to_workspace:
                root: .
                paths:
                  - www
      - unless:
          condition: << parameters.package >>
          steps:
            - run:
                name: Building
                command: npm run build
            - run:
                name: Updating Chrome
                command: |
                  wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
                  sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
                  sudo apt-get update
                  sudo apt-get install google-chrome-stable
            - run:
                name: Running unit tests
                command: npm run test -- --configuration ci
            - run:
                name: Running e2e tests
                command: npm run e2e
            - store_test_results:
                path: test-results
            - scan
  server:
    parameters:
      path:
        type: string
        default: server
      package:
        type: boolean
        default: false
    executor: java-node
    working_directory: ~/project/<< parameters.path >>
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          << : *cache-key-gradle
      - when:
          condition: << parameters.package >>
          steps:
            - attach_workspace:
                at: /tmp/workspace
            - run:
                name: Copying resources
                command: mkdir -p src/main/resources/static && cp -R /tmp/workspace/www/* src/main/resources/static
            - run:
                name: Building and Packaging
                command: ./gradlew bootJar
            - persist_to_workspace:
                root: .
                paths:
                  - build/libs
      - unless:
          condition: << parameters.package >>
          steps:
            - run:
                name: Building
                command: ./gradlew build
            - store_test_results:
                path: build/test-results
            - scan
      - save_cache:
          << : *cache-key-gradle
          paths:
            - ~/.gradle
