version: 2.1

description: |
  Build and publish Ionic/Angular libraries.
  Repository: https://github.com/okode/orbs

orbs:
  common: okode/common@volatile

executors:
  node:
    docker:
      - image: circleci/node:12
  browsers:
    docker:
      - image: circleci/node:12-browsers

jobs:
  test:
    parameters:
      project:
        type: string
    executor: browsers
    steps:
      - checkout
      - common/node-upgrade
      - common/npm-install
      - run:
          name: Building
          command: npm run build -- << parameters.project >>
      - run:
          name: Running unit tests
          command: npm run test -- << parameters.project >> --watch false --progress false
  build:
    parameters:
      project:
        type: string
    executor: node
    steps:
      - checkout
      - common/node-upgrade
      - common/npm-install
      - run:
          name: Building
          command: npm run build -- << parameters.project >>
      - persist_to_workspace:
          root: .
          paths:
            - dist
  publish-npm:
    parameters:
      path:
        type: string
      access:
        type: string
        default: public
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Installing NPM CLI Login
          command: sudo npm install -g npm-cli-login
      - run:
          name: Authenticating NPM
          command: npm-cli-login
      - run:
          name: Publishing NPM package
          command: cd << parameters.path >> && npm publish --access=<< parameters.access >>
  publish-bitbucket:
    parameters:
      path:
        type: string
      repo:
        type: string
      ssh-permission-fingerprint:
        type: string
        default: ''
    executor: node
    steps:
      - add_ssh_keys:
          fingerprints:
            - "<< parameters.ssh-permission-fingerprint >>"
      - attach_workspace:
          at: .
      - run:
          name: Publish NPM package at Bitbcuket
          command: |
            mkdir ~/.ssh/ && echo -e "Host bitbucket.org\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git clone -q git@bitbucket.org:<< parameters.repo >>-dist.git npmdist
            cd npmdist
            rm -rf *
            cp -R ../<< parameters.path >>/* .
            git add --all
            git commit -m "Bumped version $CIRCLE_TAG" || true
            git tag $CIRCLE_TAG || true
            git push && git push --tags || true
